hydra:
  job:
    chdir: True
  run:
    dir: ./output/adaptation_wall/${algo_name}/${now:%Y-%m-%d_%H%M%S_%f}

seed: 42
algo_name: ???
path: ???
num_iterations: 4_000
log_period: 10
env_batch_size: 256
action_repeat: 1

# SAC
warmup_steps: 10_000
hidden_layer_sizes: [64, 64]
grad_updates_per_step: 1.
batch_size: 256
replay_buffer_size: 1_024_000
discount: 0.99
reward_scaling: 1.0
learning_rate: 0.001
soft_tau_update: 0.005
alpha_init: 1.0
fix_alpha: False
normalize_observations: False
